# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=30, null=True)),
                ('Phone', models.CharField(default=None, max_length=12, null=True)),
                ('Email', models.EmailField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Friend1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_friend', to='task1.Contact')),
                ('Friend2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_friend', to='task1.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Occupation', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task1.Application')),
                ('App2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task1.Product')),
                ('App3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task1.Contact')),
                ('App4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='task1.Profession')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='profession',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='task1.Profession'),
        ),
        migrations.AddField(
            model_name='application',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task1.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([('Email', 'Phone')]),
        ),
    ]
